#pragma once
#include <iostream>

namespace RandomizerVariables {
    static const char* TRACK_NAMES[64] = {
    "AUTUMN HILL FORWARD",
    "AUTUMN MOUNTAIN FORWARD",
    "VICTORIA GARDEN FORWARD",
    "VICTORIA ROAD FORWARD",
    "ROUTE de la SEINE FORWARD",
    "BURGENSCHLUCHT FORWARD",
    "WINTERTRAUM FORWARD",
    "MARCO STRADA WET FORWARD",
    "MARCO STRADA FORWARD",
    "TSUKUBA FORWARD",
    "TSUKUBA NIGHT FORWARD",
    "TSUKUBA WET FORWARD",
    "NORDSCHLEIFE FORWARD",
    "SAN FRANCHISCO FORWARD",
    "LOWENSEERING FORWARD",
    "REV CITY FORWARD",
    "SPEEDIAPOLIS RING",
    "MYSTIC CAVEWAY FORWARD",
    "EDGE OF THE ROAD FORWARD",
    "DRAGON RANGE UPHILL",
    "AIRPORT SQUARE",
    "OCEAN BRIDGE TA",
    "OCEAN BRIDGE RAIN TA",
    "MIRAGE #1",
    "MIRAGE #2",
    "MIRAGE #3",
    "MIRAGE #4",
    "MIRAGE #5",
    "MIRAGE #6",
    "MIRAGE #7",
    "MIRAGE #8",
    "MIRAGE #9",
    "MIRAGE #10",
    "MIRAGE #11",
    "MIRAGE #12",
    "MIRAGE #13",
    "MIRAGE #14",
    "MIRAGE #15",
    "MIRAGE #16",
    "COSMIC EGGWAY FORWARD",
    "COSMIC WINDING FORWARD",
    "WILD WEST ENDURO FORWARD",
    "AUTUMN HILL REVERSE",
    "AUTUMN MOUNTAIN REVERSE",
    "VICTORIA GARDEN REVERSE",
    "VICTORIA ROAD REVERSE",
    "ROUTE de la SEINE REVERSE",
    "BURGENSCHLUCHT REVERSE",
    "WINTERTRAUM REVERSE",
    "MARCO STRADA WET REVERSE",
    "MARCO STRADA REVERSE",
    "TSUKUBA REVERSE",
    "TSUKUBA NIGHT REVERSE",
    "TSUKUBA WET REVERSE",
    "NORDSCHLEIFE REVERSE",
    "SAN FRANCHISCO REVERSE",
    "LOWENSEERING REVERSE",
    "REV CITY REVERSE",
    "MYSTIC CAVEWAY REVERSE",
    "EDGE OF THE ROAD REVERSE",
    "DRAGON RANGE DOWNHILL",
    "COSMIC EGGWAY REVERSE",
    "COSMIC WINDING REVERSE",
    "WILD WEST ENDURO REVERSE (NO LIGHTING)",
    };

    static const uint8_t TRACK_ID[64] = {
        1,   // AUTUMN HILL FORWARD
        2,   // AUTUMN MOUNTAIN FORWARD
        3,   // VICTORIA GARDEN FORWARD
        4,   // VICTORIA ROAD FORWARD
        5,   // ROUTE de la SEINE FORWARD
        7,   // BURGENSCHLUCHT FORWARD
        8,   // WINTERTRAUM FORWARD
        10,  // MARCO STRADA WET FORWARD
        11,  // MARCO STRADA FORWARD
        12,  // TSUKUBA FORWARD
        13,  // TSUKUBA NIGHT FORWARD
        14,  // TSUKUBA WET FORWARD
        15,  // NORDSCHLEIFE FORWARD
        16,  // SAN FRANCHISCO FORWARD
        17,  // LOWENSEERING FORWARD
        18,  // REV CITY FORWARD
        20,  // SPEEDIAPOLIS RING
        21,  // MYSTIC CAVEWAY FORWARD
        22,  // EDGE OF THE ROAD FORWARD
        23,  // DRAGON RANGE UPHILL
        26,  // AIRPORT SQUARE
        28,  // OCEAN BRIDGE TA
        29,  // OCEAN BRIDGE RAIN TA
        30,  // MIRAGE #1
        31,  // MIRAGE #2
        32,  // MIRAGE #3
        33,  // MIRAGE #4
        34,  // MIRAGE #5
        35,  // MIRAGE #6
        36,  // MIRAGE #7
        37,  // MIRAGE #8
        38,  // MIRAGE #9
        39,  // MIRAGE #10
        40,  // MIRAGE #11
        41,  // MIRAGE #12
        42,  // MIRAGE #13
        43,  // MIRAGE #14
        44,  // MIRAGE #15
        45,  // MIRAGE #16
        46,  // COSMIC EGGWAY FORWARD
        47,  // COSMIC WINDING FORWARD
        48,  // WILD WEST ENDURO FORWARD
        201, // AUTUMN HILL REVERSE
        202, // AUTUMN MOUNTAIN REVERSE
        203, // VICTORIA GARDEN REVERSE
        204, // VICTORIA ROAD REVERSE
        205, // ROUTE de la SEINE REVERSE
        207, // BURGENSCHLUCHT REVERSE
        208, // WINTERTRAUM REVERSE
        210, // MARCO STRADA WET REVERSE
        211, // MARCO STRADA REVERSE
        212, // TSUKUBA REVERSE
        213, // TSUKUBA NIGHT REVERSE
        214, // TSUKUBA WET REVERSE
        215, // NORDSCHLEIFE REVERSE
        216, // SAN FRANCHISCO REVERSE
        217, // LOWENSEERING REVERSE
        218, // REV CITY REVERSE
        221, // MYSTIC CAVEWAY REVERSE
        222, // EDGE OF THE ROAD REVERSE
        223, // DRAGON RANGE DOWNHILL
        246, // COSMIC EGGWAY REVERSE
        247, // COSMIC WINDING REVERSE
        248, // WILD WEST ENDURO REVERSE (NO LIGHTING)
    };

    static const int TRACK_ADDRESS_EL = 0x01ab7c44;
    static const int TRACK_ADDRESS_OTHER = 0x01af7be4;

    static const int LAPS_ADDRESS_EL = 0x01ab7c50;

    static const int DRIVER_MODE_EL = 0x0173F0B4;
    static const int INSTANT_WIN_EL = 0x01740AA0;
};